name: Publish to Maven Central (macOS)

on:
  push:
    branches:
      - master
    tags:
      - '**'  # Permet aussi de déclencher le workflow lors du push de tags

jobs:
  publish:
    runs-on: macos-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout
        uses: actions/checkout@v4

      # Étape 2 : Installer la version de Java
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Étape 3 : Installer Gradle (actions officielles Gradle)
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4


      # Étape 5 : Publier sur Maven Central
      - name: Publish to Maven Central
        run: ./gradlew publishAndReleaseToMavenCentral
        env:
          ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
          ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID }}
          ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}

